In [2]:
import pandas as pd
import numpy as np

In [3]:
df_estudiantes=pd.read_csv("/content/drive/MyDrive/StudentsPerformance (1).csv")
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
#Operaciones en columnas
#Lo primero que debemos elegir es las columnas, ojala que se numÃ©rica
df_estudiantes["reading score"]

0      72
1      90
2      95
3      57
4      78
       ..
995    99
996    55
997    71
998    78
999    86
Name: reading score, Length: 1000, dtype: int64

In [5]:
#Â¿CÃ³mo sumar datos de una columna?
df_estudiantes["reading score"].sum()

69169

In [6]:
#Â¿CÃ³mo contar datos de una columna?
df_estudiantes["reading score"].count()

1000

In [7]:
#Para calcular el promedio usamos el mÃ©todo mean
df_estudiantes["reading score"].mean()

69.169

In [8]:
#Para calcular la desviaciÃ³n estandar de una columna, uso el mÃ©todo sd
df_estudiantes["reading score"].std()

14.60019193725222

In [9]:
#Para ver las medidad de tendencia central de la tabla
df_estudiantes["reading score"].describe()

count    1000.000000
mean       69.169000
std        14.600192
min        17.000000
25%        59.000000
50%        70.000000
75%        79.000000
max       100.000000
Name: reading score, dtype: float64

In [10]:
#Operaciones entre filas, empecemos con la suma
df_estudiantes["math score"]+df_estudiantes["writing score"]+df_estudiantes["reading score"]

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [11]:
#AsÃ­ guardo una nueva columna calculada
df_estudiantes["Total"]=df_estudiantes["math score"]+df_estudiantes["writing score"]+df_estudiantes["reading score"]
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [12]:
#Ahora vamos a calcular el promedio de los datos de estass personas
(df_estudiantes["Total"]/3)

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Name: Total, Length: 1000, dtype: float64

In [13]:
df_estudiantes["Promedio"]=(df_estudiantes["Total"]/3)
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000

In [14]:
#AsÃ­ es como formateo los nÃºmero para que tenga solo dos decimales
df_estudiantes.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.67
1,female,group C,some college,standard,completed,69,90,88,247,82.33
2,female,group B,master's degree,standard,none,90,95,93,278,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.33
4,male,group C,some college,standard,none,76,78,75,229,76.33
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.00
996,male,group C,high school,free/reduced,none,62,55,55,172,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.00
998,female,group D,some college,standard,completed,68,78,77,223,74.33
999,female,group D,some college,free/reduced,none,77,86,86,249,83.00

In [15]:
#Ahora vamos a contar elementos por valor
len(df_estudiantes["gender"])

1000

In [16]:
#Para cada uno uso el mÃ©todo value.counts
df_estudiantes["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [17]:
#Para contar la raza y  grupos etnicos (en este caso)
df_estudiantes["race/ethnicity"].value_counts()

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [18]:
#AsÃ­ puedo calcular el valor de participaciÃ³n por cada elemento
df_estudiantes["race/ethnicity"].value_counts(normalize=True*100)

race/ethnicity
group C    0.319
group D    0.262
group B    0.190
group E    0.140
group A    0.089
Name: proportion, dtype: float64

In [19]:
df_estudiantes["parental level of education"].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [37]:
df_estudiantes["parental level of education"].value_counts(normalize=True)*100

parental level of education
some college          22.6
associate's degree    22.2
high school           19.6
some high school      17.9
bachelor's degree     11.8
master's degree        5.9
Name: proportion, dtype: float64

In [22]:
df_estudiantes["gender"].value_counts(normalize=True)*100

gender
female    51.8
male      48.2
Name: proportion, dtype: float64

In [23]:
df_estudiantes["math score"].value_counts()

math score
65    36
62    35
69    32
59    32
61    27
      ..
24     1
28     1
33     1
18     1
8      1
Name: count, Length: 81, dtype: int64

In [38]:
df_estudiantes.sort_values("math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333
17,female,group B,some high school,free/reduced,none,18,32,28,78,26.000000
787,female,group B,some college,standard,none,19,38,32,89,29.666667
145,female,group C,some college,free/reduced,none,22,39,33,94,31.333333
...,...,...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99,296,98.666667
623,male,group A,some college,standard,completed,100,96,86,282,94.000000
451,female,group E,some college,standard,none,100,92,97,289,96.333333
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000
149,male,group E,associate's degree,free/reduced,completed,100,100,93,293,97.666667

In [50]:
#Ahora vamos a organizar de forma descendente
df_estudiantes.sort_values(["math score"], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000
625,male,group D,some college,standard,completed,100,97,99,296,98.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000
623,male,group A,some college,standard,completed,100,96,86,282,94.000000
451,female,group E,some college,standard,none,100,92,97,289,96.333333
...,...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,94,31.333333
787,female,group B,some college,standard,none,19,38,32,89,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,78,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000

In [31]:
#TambiÃ©n podemos irdenar los DataFrame no solo por una columna sino por dos
#Hay que tener en cuenta, que organizarÃ¡ por le primer dato y el segundo serÃ¡ dependiente
df_estudiantes.sort_values(["reading score", "writing score"], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
106,female,group D,master's degree,standard,none,87,100,100,287,95.666667
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667
165,female,group C,bachelor's degree,standard,completed,96,100,100,296,98.666667
179,female,group D,some high school,standard,completed,97,100,100,297,99.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000
...,...,...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22,78,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000

In [34]:
organizado_lectura=df_estudiantes.sort_values(["reading score", "writing score"], ascending=False)
organizado_lectura

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
106,female,group D,master's degree,standard,none,87,100,100,287,95.666667
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667
165,female,group C,bachelor's degree,standard,completed,96,100,100,296,98.666667
179,female,group D,some high school,standard,completed,97,100,100,297,99.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000
...,...,...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22,78,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000

In [36]:
organizado_lectura.to_csv("organizado_lectura.csv", index=False)

In [53]:
#De esta manera puedo guardar los datos y sobre-escribir, sein reusar la variable con el mÃ©todo
df_estudiantes.sort_values(["reading score","writing score"], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
106,female,group D,master's degree,standard,none,87,100,100,287,95.666667
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667
165,female,group C,bachelor's degree,standard,completed,96,100,100,296,98.666667
179,female,group D,some high school,standard,completed,97,100,100,297,99.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000
...,...,...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22,78,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000

In [66]:
#Vamos a organizar los valores por texto, para eso usaremos la funciÃ³n lampda
#Con ella convertimos primero los valores en minÃºsculas y luego ordenamos
df_estudiantes.sort_values("race/ethnicity", ascending=True,
                           key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total,Promedio
778,female,group A,some college,standard,completed,72,79,82,233,77.666667
546,female,group A,some high school,standard,completed,92,100,97,289,96.333333
820,female,group A,some high school,standard,completed,85,90,92,267,89.000000
741,female,group A,associate's degree,free/reduced,none,37,57,56,150,50.000000
305,male,group A,some college,standard,none,69,67,69,205,68.333333
...,...,...,...,...,...,...,...,...,...,...
297,male,group E,associate's degree,standard,completed,71,74,68,213,71.000000
293,female,group E,bachelor's degree,standard,none,65,73,75,213,71.000000
289,male,group E,some high school,standard,completed,77,76,77,230,76.666667
206,male,group E,bachelor's degree,standard,none,82,62,62,206,68.666667
499,male,group E,some college,standard,none,76,71,72,219,73.000000